<a href="https://colab.research.google.com/github/dipanshuhaldar/pytorch_basics/blob/master/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PyTorch Basics: Tensors & Gradients**

In [1]:
#import Pytorch library
import torch
print(f'{torch.__version__}')

1.5.0+cu101


**Tensors**

At its core, PyTorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array. Let's create a tensor with a single number:

In [0]:
#number
t1 = torch.tensor(4.0)
t1

tensor(4.)

4. is a shorthand for 4.0. It is used to indicate to Python (and PyTorch) that you want to create a floating point number. We can verify this by checking the dtype attribute of our tensor:

In [0]:
print(f'data type of t1 is: {t1.dtype}')

data type of t1 is: torch.float32


Let's try creating slightly more complex tensors:

In [0]:
#vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [0]:
#matrix
t3 = torch.tensor([
                   [5., 6],
                   [7, 8],
                   [9, 10]
])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [0]:
#3-dimensional array
t4 = torch.tensor([
                   [[11., 12, 13], [13, 14, 15]],
                   [[15, 16, 17], [17, 18,19]]
])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

Tensors can have any number of dimensions, and different lengths along each dimension. We can inspect the length along each dimension using the .shape property of a tensor.

In [0]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [0]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [0]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [0]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

We've created 3 tensors x, w and b, all numbers. w and b have an additional parameter requires_grad set to True. We'll see what it does in just a moment.

Let's create a new tensor y by combining these tensors:

In [0]:
#create tensors
x = torch.tensor(3.)
#x = torch.tensor(3., requires_grad = True)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)

In [0]:
#arithmatic operation
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, y is a tensor with the value 3 * 4 + 5 = 17. What makes PyTorch special is that we can automatically compute the derivative of y w.r.t. the tensors that have requires_grad set to True i.e. w and b. To compute the derivatives, we can call the .backward method on our result y.

In [0]:
#compute derivaives
y.backward()

In [0]:
#display gradients
print(f'dy/dx: {x.grad}')
print(f'dy/dw: {w.grad}')
print(f'dy/db: {b.grad}')

dy/dx: None
dy/dw: 3.0
dy/db: 1.0


As expected, dy/dw has the same value as x i.e. 3, and dy/db has the value 1. Note that x.grad is None, because x doesn't have requires_grad set to True.

The "grad" in w.grad stands for gradient, which is another term for derivative, used mainly when dealing with matrices.

**Interoperability with Numpy**

Numpy is a popular open source library used for mathematical and scientific computing in Python. It enables efficient operations on large multi-dimensional arrays, and has a large ecosystem of supporting libraries:

Matplotlib for plotting and visualization
OpenCV for image and video processing
Pandas for file I/O and data analysis
Instead of reinventing the wheel, PyTorch interoperates really well with Numpy to leverage its existing ecosystem of tools and libraries.

Here's how we create an array in Numpy:

In [0]:
import numpy as np
x = np.array([[1., 2],[3, 4]])
x

array([[1., 2.],
       [3., 4.]])

We can convert a Numpy array to a PyTorch tensor using torch.from_numpy.

In [0]:
#convert numpy array to torch tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [0]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert a PyTorch tensor to a Numpy array using the .numpy method of a tensor.

In [0]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

The interoperability between PyTorch and Numpy is really important because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.